# Generated by Django 3.0.6 on 2020-05-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Introduce product title', max_length=200)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='Introduce a brief description for the product')),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
