# Generated by Django 3.0.6 on 2020-05-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200515_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('country', models.CharField(choices=[('US', 'us'), ('SPAIN', 'es')], max_length=100)),
                ('state', models.CharField(choices=[('California', 'ca'), ('Barcelona', 'bcn')], max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('items', models.CharField(max_length=1000)),
            ],
        ),
    ]
